import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "./index.module.css";
import Link from "next/link";

import { Button } from "../components/Button";
import { Header } from "../components/Header";
import { Footer } from "../components/Footer";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className={`${styles.main} ${inter.className}`}>
        <div>
          <div className={styles.title}>
            <h1>Hello, World!!</h1>
          </div>
          <div>
            <Link className={styles.tag} href="/works">
              各作品
            </Link>
            <Link className={styles.tag} href="./search">
              検索欄
            </Link>
            <Link className={styles.tag} href="./post">
              投稿ページ
            </Link>
            <div className={styles.tag}>
              <Button onClick={() => location.replace("./login")}>
                ログインページ
              </Button>
            </div>
          </div>

          {(function () {
            const list = [];
            for (let i = 0; i < 10; i++) {
              list.push(
                <div className={styles.post}>
                  <h1>post</h1>
                </div>
              );
            }
            return <ul className={styles.a}>{list}</ul>;
          })()}
        </div>
      </main>
      <Footer />
    </>
  );
}
